name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '20??.3.*'
      - '20??.6.*'
      - '20??.9.*'
      - '20??.12.*'
  pull_request:
    branches:
      - '20??.3.x'
      - '20??.6.x'
      - '20??.9.x'
      - '20??.12.x'


jobs:

  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Docker Login
        run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Test Docker Image
        run: docker build -t test-image --target run-stage .

      - name: Lint Code in Container
        run: docker run test-image yarn lint

      - name: Test Code in Container
        run: docker run test-image yarn test

      - name: Docker Logout
        run: docker logout
