name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '20[0-9]+.3.*'
      - '20[0-9]+.6.*'
      - '20[0-9]+.9.*'
      - '20[0-9]+.12.*'
  pull_request:
    branches:
      - '20[0-9]+.3.x'
      - '20[0-9]+.6.x'
      - '20[0-9]+.9.x'
      - '20[0-9]+.12.x'


jobs:

  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Docker Login
        run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Test Docker Image
        run: docker build -t test-image --target run-stage .

      - name: Lint Code in Container
        run: docker run test-image yarn lint

      - name: Test Code in Container
        run: docker run test-image yarn test

      - name: Docker Logout
        run: docker logout
