name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '20[0-9][0-9].3.*'
      - '20[0-9][0-9].6.*'
      - '20[0-9][0-9].9.*'
      - '20[0-9][0-9].12.*'
  pull_request:
    branches:
      - '20[0-9][0-9].3.x'
      - '20[0-9][0-9].6.x'
      - '20[0-9][0-9].9.x'
      - '20[0-9][0-9].12.x'


jobs:

  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Docker Login
        run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Test Docker Image
        run: docker build -t test-image --target run-stage .

      - name: Lint Code in Container
        run: docker run test-image yarn lint

      - name: Test Code in Container
        run: docker run test-image yarn test:unit

      - name: Docker Logout
        run: docker logout


  tar:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') || (github.ref == secrets.DEFAULT_BRANCH) }}
    needs:
      - test
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Docker Login
        run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Test Docker Image
        run: docker build -t build-image --target build-stage .

      - name: Copy Dist Folder
        run: docker cp build-image:/app/dist .

      - name: Compress tar.gz
        run: |
          if [[ $GITHUB_REF =~ ^refs/tags/(.*)$ ]]
          then
            VERSION=${BASH_REMATCH[1]}
          elif [[ $GITHUB_REF =~ ^refs/heads/(.*)$ ]]
          then
            VERSION=${BASH_REMATCH[1]}
          else
            exit 1
          fi
          RELEASE="corteza-webapp-one-$VERSION.tar.gz"
          tar -C dist -czf $RELEASE $(dir dist)

      - name: Install lftp
        run: apt-get install lftp -y

      - name: Upload tar.gz
        run: lftp sftp://${{ secrets.SOURCEFORGE_USERNAME }}:${{ secrets.SOURCEFORGE_PASSWORD }}@frs.sourceforge.net:/home/frs/project/cortezaproject/corteza-webapp-one -e "put $RELEASE; bye"

      - name: Docker Logout
        run: docker logout


  docker:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') || (github.ref == secrets.DEFAULT_BRANCH) }}
    needs:
      - test
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Docker Login
        run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          if [[ $GITHUB_REF =~ ^refs/tags/(.*)$ ]]
          then
            TAG=${BASH_REMATCH[1]}
          elif [[ $GITHUB_REF =~ ^refs/heads/(.*)$ ]]
          then
            TAG=${BASH_REMATCH[1]}
          else
            exit 1
          fi
          IMAGE="cortezaproject/corteza-webapp-one:$TAG"
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Docker Logout
        run: docker logout
